// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mission4Assignment.Models;

namespace Mission4Assignment.Migrations
{
    [DbContext(typeof(MoviesContext))]
    [Migration("20220126001545_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.22");

            modelBuilder.Entity("Mission4Assignment.Models.NewMovie", b =>
                {
                    b.Property<int>("MovieId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .HasColumnType("TEXT");

                    b.Property<string>("Director")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Edited")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LentTo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("Rating")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.Property<short>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("MovieId");

                    b.ToTable("Responses");

                    b.HasData(
                        new
                        {
                            MovieId = 1,
                            Category = "Superhero",
                            Director = "Anthony and Joe Russo",
                            Edited = false,
                            Rating = "PG-13",
                            Title = "Avengers: Endgame",
                            Year = (short)2019
                        },
                        new
                        {
                            MovieId = 2,
                            Category = "Drama",
                            Director = "Gabriele Muccino",
                            Edited = false,
                            Rating = "PG-13",
                            Title = "The Pursuit of Happyness",
                            Year = (short)2006
                        },
                        new
                        {
                            MovieId = 3,
                            Category = "Adventure",
                            Director = "Ben Stiller",
                            Edited = false,
                            Rating = "PG",
                            Title = "The Secret Life of Walter Mitty",
                            Year = (short)2013
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
