// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mission4Assignment.Models;

namespace Mission4Assignment.Migrations
{
    [DbContext(typeof(MoviesContext))]
    [Migration("20220202153540_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.22");

            modelBuilder.Entity("Mission4Assignment.Models.Category", b =>
                {
                    b.Property<int>("CategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CategoryName")
                        .HasColumnType("TEXT");

                    b.HasKey("CategoryID");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryID = 1,
                            CategoryName = "Superhero"
                        },
                        new
                        {
                            CategoryID = 2,
                            CategoryName = "Drama"
                        },
                        new
                        {
                            CategoryID = 3,
                            CategoryName = "Adventure"
                        },
                        new
                        {
                            CategoryID = 4,
                            CategoryName = "Action"
                        },
                        new
                        {
                            CategoryID = 5,
                            CategoryName = "Comedy"
                        },
                        new
                        {
                            CategoryID = 6,
                            CategoryName = "Fantasy"
                        },
                        new
                        {
                            CategoryID = 7,
                            CategoryName = "Horror"
                        },
                        new
                        {
                            CategoryID = 8,
                            CategoryName = "Mystery"
                        },
                        new
                        {
                            CategoryID = 9,
                            CategoryName = "Romance"
                        },
                        new
                        {
                            CategoryID = 10,
                            CategoryName = "Thriller"
                        },
                        new
                        {
                            CategoryID = 11,
                            CategoryName = "Western"
                        });
                });

            modelBuilder.Entity("Mission4Assignment.Models.NewMovie", b =>
                {
                    b.Property<int>("MovieId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Director")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Edited")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LentTo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT")
                        .HasMaxLength(25);

                    b.Property<string>("Rating")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<short>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("MovieId");

                    b.HasIndex("CategoryID");

                    b.ToTable("Responses");

                    b.HasData(
                        new
                        {
                            MovieId = 1,
                            CategoryID = 1,
                            Director = "Anthony and Joe Russo",
                            Edited = false,
                            LentTo = "",
                            Notes = "",
                            Rating = "PG-13",
                            Title = "Avengers: Endgame",
                            Year = (short)2019
                        },
                        new
                        {
                            MovieId = 2,
                            CategoryID = 2,
                            Director = "Gabriele Muccino",
                            Edited = false,
                            LentTo = "",
                            Notes = "",
                            Rating = "PG-13",
                            Title = "The Pursuit of Happyness",
                            Year = (short)2006
                        },
                        new
                        {
                            MovieId = 3,
                            CategoryID = 3,
                            Director = "Ben Stiller",
                            Edited = false,
                            LentTo = "",
                            Notes = "",
                            Rating = "PG",
                            Title = "The Secret Life of Walter Mitty",
                            Year = (short)2013
                        });
                });

            modelBuilder.Entity("Mission4Assignment.Models.NewMovie", b =>
                {
                    b.HasOne("Mission4Assignment.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
